build: false
platform:
  - x64
clone_folder: C:\projects\joomla-cms

branches:
  except:
    - /l10n_*/

## Build matrix for lowest and highest possible targets
environment:
  DLLVersion: "5.6.1"
  PHPBuild: "x64"
  VC: "vc15"
  matrix:
  - php_ver_target: 7.2
    DLLVersion: "5.3.0"
  - php_ver_target: 7.3

init:
  - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1 # This var relates to caching the php  install
  - SET ANSICON=121x90 (121x90)
services:
  - mssql2014
  - mysql
  - postgresql94
  - iis

install:
  - ps: $my_variable = choco search php --exact --all-versions -r

test_script:
  - ps: Write-Host "This is $my_variable"
  - cd C:\projects\joomla-cms
